SELECT * FROM customer_behavior

--Total revenue generated by male and female customers--
select gender,sum(purchase_amount)
from customer_behavior
group by gender

--Which customers used discount but still spend more than the avg purchase amount?--
select customer_id,purchase_amount
from customer_behavior
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customer_behavior)

--Which are the top 5 products having highest avg review rating?--
select item_purchased,round(avg(review_rating::numeric),2) as "Avg product rating"
from customer_behavior
group by item_purchased
order by avg(review_rating) desc
limit 5

--Compare the avg purchase amount bw express and Standard shipping?--
select shipping_type,
round(avg(purchase_amount),2)
from customer_behavior
where shipping_type in ('Standard','Express')
group by shipping_type
 
--Do subscribed customers spend more? Compare avg spend and total revenue bw subscribers and non-subscribers?--
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_Revenue
from customer_behavior
group by subscription_status
order by total_Revenue,avg_spend desc

--Which 5 products have the highest % of purchases with discounts applied?--
select item_purchased,
round(100* sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer_behavior
group by item_purchased
order by discount_rate desc
limit 5

--Segment customers as New, returning and loyal based on their total no. of purchases and show the count of each segment?--
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_behavior
)
SELECT 
    customer_segment,
    COUNT(*) AS "No.of customers"
FROM customer_type
GROUP BY customer_segment;

--What are the top 3 most purchased products in each category?--
with item_counts as(
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) DESC ) as item_rank
from customer_behavior
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3

--Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe  
select subscription_status,
count(customer_id) as repeat_buyers
from customer_behavior
where previous_purchases>5
group by subscription_status

--What is the revenue contribution of each age group?--
select age_group,
sum(purchase_amount)as total_revenue
from customer_behavior
group by age_group
order by total_revenue desc







